### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by girokarambole1453** [apastel/ytmusic-deleter#27]
I am new to the github sorry if here is not the place for me to post this:( Can someone explain me how secure is it to share(when i input the .json file) a cookie of mine? Also is there a command to clear artists from library too?

**Comment by apastel** [comment]
Good question, never hurts to ask. This tool I made uses the [ytmusicapi](https://github.com/sigma67/ytmusicapi) under the hood, which is a Python-based API for doing stuff with a YTMusic library. My ytmusic-deleter just uses that API to do everything, so it follows the same procedure that that API uses, which they've documented here: https://ytmusicapi.readthedocs.io/en/stable/setup/browser.html

Using the request header information that you paste in, the API is able to emulate a logged-in browser. So those headers contain everything the API needs to perform read/write operations on your library. The important part here is that this software runs on your computer, and the software doesn't share your request headers with anyone else on the internet, or upload them anywhere or anything. Think of it I guess like your car keys. Anyone who has your car keys can potentially steal your car, but as long as you don't give them out to anybody or leave them somewhere, then it's fine. And since this is all open-source software, anyone is welcome to look through the source code to confirm that nobody is stealing your keys.

2nd question, by "clear artists", do you mean delete all the songs and albums of one particular artist?

**Comment by girokarambole1453** [comment]
apastel first of all thank you so much for explaining me the process and making me comfortable :) 2.  by "clear artists" I meant when I go to library there is a artists section and when I click it there are some artists I listened looong time ago, that some of their songs in my library somehow. I dont listen to them rn so I want to clear my artists section is it possible?

**Comment by apastel** [comment]
Well, so the main purpose of the tool is to delete *everything*. It works by deleting every one of your albums. And if you delete every one of your albums, then all of your artists themselves would be gone. In YTMusic, an "Artist" is really just a collection of albums associated with one particular musician. So yes if you run the tool `delete-uploads` and/or `delete-library` commands, all your artists would be gone too.

**Comment by girokarambole1453** [comment]
Thank you so much for the support man, I love you! And thank you for this whole project :) Good Luck, Have a nice day!❤
