### ISSUE TITLE
Can't authenticate the application

### ISSUE THREAD

**Issue by COMMANDERWONG** [apastel/ytmusic-deleter#28]
I tried to find that POST request as the document said. But that particular request can't be found. What should I do?

**Comment by apastel** [comment]
Any time you click **any** button in YT Music. the POST request will appear. So the issue is that you must not be seeing it.

Are you seeing other requests, and just not that particular request? A screenshot of your Network tab in the Developer Toolbar  would help.

Both Firefox and Chrome have a filter bar too in the Network tab. So in Firefox for example you can filter for `method:POST` and only the POST requests will appear.

**Comment by apastel** [comment]
For posterity, anyone else having trouble with this can watch me do it in this video: https://youtu.be/f4RTUZ6kLUI?si=Rh_qzc21LS3xuw-e&t=60
