### ISSUE TITLE
Works, but doesn't delete everythong in one go.

### ISSUE THREAD

**Issue by spkdaztek** [apastel/ytmusic-deleter#61]
Hey man, I went from 10k to almost 500 songs but I've been the whole day at it. Certainly not the fastest way but at least I don't have to keep tabs open. Anyway, at some point it managed to go from 7k down to 2k and now it unlikes like 20 songs per try. I've noticed there are less songs in my library overall, but since yt music doesn't give an exact number I can't really tell.

[Here's](https://drive.google.com/file/d/1_PJoMC7Be1QrkOAgdO1toUyzNv5Okm9B/view?usp=drive_link) the log from the last try. The log was too long for github

**Comment by apastel** [comment]
Ok, so two separate issues happening here so I'll try to address both separately, since unliking songs and removing library tracks are two separate things. You might also want to test them separately going forward by using the "Remove Library" and "Unlike All" buttons, instead of "Delete All".

1. Remove all library albums: `Unable to find 'navigationEndpoint'` error

_tl;dr Check if you have the "two column" layout or the "single column" layout for albums.._

> [2024-07-21 10:30:03] Retrieving all library albums...
[2024-07-21 10:30:04] Retrieved 0 albums from your library.
[2024-07-21 10:30:04] Retrieving all singles...
[2024-07-21 10:30:04] Retrieved 44 singles from your library.

According to this, there are no more full albums in your library and what remains are just 44 "singles". Now, a single could have multiple tracks on it, but typically it's just a few. So by the looks of this, there must not many songs left in your library, maybe a few hundred. If that sounds incorrect, show me a screenshot of your library albums like this:
![image](https://github.com/user-attachments/assets/e1c3f122-ade0-4166-b0d0-f5795512f83f)

Now, addressing that error that's happening. It seems like the `ytmusicapi` that my tool uses is assuming that you have the "two column" layout for albums. I think that API assumes everybody has been migrated to the two column layout, but it's possible you may still have the single column layout. Here is an example of what I mean by "two column layout":

![image](https://github.com/user-attachments/assets/7f972350-71dd-4464-ab64-492c4366fa6f)

See how the album info is on the left, and the track list is on the right? Those are the two columns. It _used_ to be a single column with the album on top and the tracklist beneath it, then Google changed it and that changed how the API works. So do me a favor and click on one of your remaining albums or singles and tell me (or paste a screenshot) of whether the album info and tracklist are in two columns like mine, or a single column. That will help determine if that's why it's failing to delete each one of your remaining singles/albums.

A lot of the other errors are with encoding non-US keyboard characters and I think those are just causing logging errors and not actually preventing song removal.

============================

2. Unlike all songs

_tl;dr: Check how many songs are listed in the "Your Likes" playlist and use the "Unlike All" button in YTMusic Deleter_

For the unliking of the songs (which happens after the removing of library albums), you mentioned it's only doing like 20 songs per try. In the log you sent me, it found 333 and it unliked 288 of them. The remaining 45 were skipped because they did not have an album associated with them, so it considered them to be a YouTube video and not an actual song on YouTube Music. I can reconsider whether those should be unliked if you think that it should be unliking those as well. But the main issue you're saying is that you have thousands of songs that are still in your "Liked Music" playlist? That is odd, since the tool should retrieve all of them at once. Try using the "Unlike All" button so that we can focus on just the unliking of songs. If you really do have thousands of liked songs remaining, you would see them in the "Your Likes" playlist and it would show the number of liked songs in the playlist info like this:
![image](https://github.com/user-attachments/assets/11bcdbcc-adc3-4358-88d3-c61e5652b93d)

So do me another favor and check the Your Likes playlist and see how many tracks it says there are remaining.

**Comment by spkdaztek** [comment]
I don't know what layout it has, I checked and there are no albums nor singles. idk what to tell you, just that this account, to my knowledge, was never used on a PC before, it was used on a really old android phone for the family bussiness.

As for the unlike all songs issue; I think I figured out what's going on. Your app skips regular yt videos but some of those videos still appear in the ytm library even when the "show yt videos" option is disabled. So I went and unliked some of those songs on yt and they dissappear on the ytm library, next I ran a script to remove all the videos from yt liked videos playlist and it took a while but it managed to remove the rest of the songs from the ytm library. 

Here's the funny part. Do you know if your app removes deleted or private videos? Because the scripts I found certainly dont. So I end up with 194 unavailable videos and when I click on any of those, turns out they were taken down due to copyright claims or the accounts were deleted.


<img width="1280" alt="yt" src="https://github.com/user-attachments/assets/00fe7a62-41d3-4860-a0cf-89c8e5f086aa">


Now I'm pretty sure that some of those videos are, somehow, still taken into consideration for the ytm library for I have 6
songs that don't show up in ytm and don't add up to the total runtime.


<img width="1280" alt="yt" src="https://github.com/user-attachments/assets/6f016b06-0f9c-422b-8c75-fb7b0670f8ee">


If I enable the "see music from youtube" the list goes up to 84, but still shows no songs and 0 hours


<img width="1280" alt="yt" src="https://github.com/user-attachments/assets/ca28b8ab-8759-4b18-9126-3d2a3c6f7d9c">
 After all this, your app retrieves 0 songs.

<img width="676" alt="yt" src="https://github.com/user-attachments/assets/d9bf676b-cbfa-4772-b8ad-7ef40f8b01d2">

Personally I think I just gotta remove all those unavailable videos on yt, maybe manually, and the ytm library will be completely erased. So there's that. Either way your app was really useful, thanks for it.

**Comment by apastel** [comment]
Hmm, if it's showing "Retrieved 0 liked songs" then there's not much my tool can do from there. It uses that [ytmusicapi](https://github.com/sigma67/ytmusicapi) to fetch all your liked songs, so if that API is fetching 0 then my tool won't be able to do anything with those. So you enabled "Show your liked music from YouTube" and it still shows an empty list huh? Maybe YouTube Music is incapable of showing "deleted videos" even though they are there. I don't think there is much you can do except manually remove those from YouTube itself. Unless maybe somebody has a script that removes tracks from Liked videos (or from playlists in general) on YouTube. Sorry that doesn't help, but sounds like my tool got you most of the way there at least.
