### ISSUE TITLE
Delete Library doesn't actually do anything

### ISSUE THREAD

**Issue by NoobishNemo** [apastel/ytmusic-deleter#62]
I downloaded today and signed in to my YTM account and ran Delete Library. It said it was removing albums and it finished successfully, but when I went back to YTM nothing was actually removed. The same amount of songs were still there that were there before I ran the tool. 

Unfortunately, the log seems to have disappeared.

**Comment by NoobishNemo** [comment]
I should add, when I did Delete All, it DID remove/delete my playlists. But nothing from my actual Library was deleted.

**Comment by NoobishNemo** [comment]
OK, I ran it again and here are the logs: 

https://pastebin.com/nm07XAyV

**Comment by apastel** [comment]
Thanks for the report. I saw the same `navigationEndpoint` error appear in another user's logs so I suspect that something in the latest [ytmusicapi](https://github.com/sigma67/ytmusicapi) might have broken, or Google changed something and the ytmusicapi has not caught up to it yet. I will have to look into that.

Based on the logs though, it's showing that the vast majority of albums are not experiencing the error and were removed. At the end, it shows the total:
> [2024-07-23 17:10:39] Removed 697 out of 758 albums and podcasts from your library.

So are you sure that **nothing** was actually removed? Because that would be a bigger issue if the API is lying about albums being removed.

For example, the following albums should no longer be in your library:

- P.O.D. - Satellite (U.S. Version WEA Distribution)
- John Mayer - Room For Squares
- Tut Tut Child - Come to the End; Then Stop
- Coldplay - Parachutes 

(I just picked a few from the end of your logs)

**Comment by NoobishNemo** [comment]
That's another interesting thing. I guess I'm not really sure what the Deleter considers an "Album". 

I can tell you there were 1175 songs in my library before I ran the Deleter above and 1175 after I ran it. There were 15 Albums in my library before and 15 after. 

I can see in my library songs from the albums you listed above are still there (see attached photos). 
![Screenshot 2024-07-23 180018](https://github.com/user-attachments/assets/6d5ca49a-10af-44f0-a72b-3ae38b47eba9)
![Screenshot 2024-07-23 175703](https://github.com/user-attachments/assets/31b183cc-42a4-4591-aadb-a51fe2f4d700)
![Screenshot 2024-07-23 175815](https://github.com/user-attachments/assets/82a8ced3-29c8-4f9c-a4ac-ed486f54fafe)
![Screenshot 2024-07-23 175900](https://github.com/user-attachments/assets/d4f8a9d1-6eb5-4afd-a57a-d1fc836e2408)

It would indeed seem that the Deleter is reporting things are being removed that weren't actually removed.

**Comment by apastel** [comment]
Alright. I can't exactly explain why that is, but I did see that they fixed this [error](https://github.com/sigma67/ytmusicapi/issues/613) recently in ytmusicapi and I just had to publish a new release of YTMusic Deleter that uses that new version of the API, so here it is:

https://github.com/apastel/ytmusic-deleter/releases

When you download that new .exe file there, it will update your existing install of YTMusic Deleter. It *should* take care of all those albums that were failing before, and it should wipe your whole library. Let me know if it doesn't.

**Comment by NoobishNemo** [comment]
That does not seem to have resolved the issue. Still seeing 1175 songs in my library, although the log did change at the end: 

[2024-07-23 18:49:59] Removed 756 out of 758 albums and podcasts from your library.
State changed: Not running
Process finished.

Here's the full log https://pastebin.com/1rz3201X

**Comment by apastel** [comment]
Ok so it resolved the `navigationEndpoint` errors as expected but bigger question is why is nothing actually being removed. 

I've never actually seen this problem before. When it says it removes something, it always removes it. And it's been working that way for years, including when I test it myself right now. :man_shrugging: 

It's possible an error is happening but not being caught by the API. I just published *another* release that will add a debug log message to every `remove_album` request.

https://github.com/apastel/ytmusic-deleter/releases/tag/2.4.6

After installing, you will just have to enable verbose logging by clicking File -> Preferences -> Enable verbose logging

**Comment by NoobishNemo** [comment]
OK, so the logs are so long they exceed the size limit for Pastebin so I had to upload a text file instead lmao
[YTMusic Deleter Logs 3.txt](https://github.com/user-attachments/files/16363538/YTMusic.Deleter.Logs.3.txt)

**Comment by apastel** [comment]
Thanks for doing that. So here's the interesting tidbit for each album/song that it's attempting to remove:

> `'successResponseText': {'runs': [{'text': 'Removed from liked music'}]}`

It says "Removed from liked music". It's supposed to say "Removed from library".

I've never seen this happen so I'm going to open a discussion with the author of [ytmusicapi](https://github.com/sigma67/ytmusicapi) and see what they think. Thanks for being patient. If this is happening for you then it's possible it can happen or is already happening for other users so thanks for working with me to get this sorted out.

**Comment by NoobishNemo** [comment]
No problem, happy to help.

**Comment by apastel** [comment]
So I have another release for you that doesn't solve the problem but adds more debug logging to help figure out what's going on.

https://github.com/apastel/ytmusic-deleter/releases/tag/2.4.7

So if you don't mind just repeating what you did previously and uploading the log file, this time it will show the ID being used to remove the album so I can compare it to mine.

**Comment by NoobishNemo** [comment]
See attached.
[YTMusic Deleter Logs 4.txt](https://github.com/user-attachments/files/16378795/YTMusic.Deleter.Logs.4.txt)

**Comment by apastel** [comment]
Thanks for that last log. That revealed what I needed to know, which is that Google is doing some testing with user's accounts, causing the API to break.

I was able to rework it though so that it uses a different method for song removal. Try this release and it may just do the trick (fingers crossed :crossed_fingers: )

https://github.com/apastel/ytmusic-deleter/releases/tag/remove-songs-individually

Note that the filename is the same as the last one but it should still update your current install.

**Comment by NoobishNemo** [comment]
That link says Page Not Found

**Comment by apastel** [comment]
My bad, it was still in Draft. I just published it now so the link should work.

**Comment by NoobishNemo** [comment]
Still showing a 404. I'll give it a couple minutes.

**Comment by apastel** [comment]
Oh I see what happened. No it wasn't a timing issue or a draft issue, I was unintentionally deleting the "tag" after publishing, not knowing it would change the link address. Ok, 3rd times the charm, try again now, sorry.

**Comment by NoobishNemo** [comment]
OK, that seems to have done the trick! My library is now clear!

**Comment by apastel** [comment]
Hell yes! Well I know that took a while to get there but thanks for staying through to the end, this will help improve the app now for others.

**Comment by NoobishNemo** [comment]
Ok, so here's another potential issue. The Deleter seems to have also
deleted my Liked Music playlist (which I didn't even realize was possible).

So when I used Soundiiz to transfer my Spotify music over it's not showing
up anywhere even though Soundiiz shows transfer complete.

**Comment by NoobishNemo** [comment]
Is there a log history somewhere?

**Comment by NoobishNemo** [comment]
OK, my other YTMusic account no longer has the "Liked Music/Liked Songs/Your Likes" playlist either, so it may not have been YTMusic Deleter that got rid of it. 

Weird.

**Comment by apastel** [comment]
If you ran the "Delete All" button, it also unlikes all of your "liked" songs. Since that "Liked Music" playlist is just a collection of your liked songs, once you have no more likes, that playlist will disappear. So if you ran "Delete All" at any point that would 100% make sense, but if not, then something else caused all your likes to disappear.

To answer your log question, the logs are kept in `%APP_DATA%\YTMusic_Deleter`, where `%APP_DATA%` is typically something like `C:\Users\your_username\AppData\Roaming`

**Comment by NoobishNemo** [comment]
I think the issue is with Soundiiz more than anything. I used TuneMyMusic instead and its working fine.
