### ISSUE TITLE
Incomplete history deletion

### ISSUE THREAD

**Issue by anthonielamay** [apastel/ytmusic-deleter#72]
Just found and installed the latest release (2.6.2).  Experiencing an issue where the program goes though and deleted the history, but only for certain periods.  In my case it deleted all but one song in March 2024, all of January and February 2024, but nothing before that.  Here is the log and a screenshot.
![Screenshot 2024-09-20 105124](https://github.com/user-attachments/assets/4c8d666c-043d-4962-9db3-55cc0aebf2f1)
[ytmusic-deleter_log.txt](https://github.com/user-attachments/files/17076861/ytmusic-deleter_log.txt)

**Comment by apastel** [comment]
Since we talked on Discord, it sounded like you were able to get it to work by running it again later, and maybe it was a rate limiting issue by the API like you said. Let me know if you are still experiencing any issues with it or if you were able to delete all your history.

**Comment by anthonielamay** [comment]
I went though and waited a few days to try again, to build up the history, and give the API a break.  Just tried to run the "Delete History", nothing found.

[2024-09-24 16:20:56] Begin deleting history...
[2024-09-24 16:20:57] https://music.youtube.com:443 "GET / HTTP/1.1" 200 None
[2024-09-24 16:20:58] https://music.youtube.com:443 "POST /youtubei/v1/browse?alt=json HTTP/1.1" 200 None
[2024-09-24 16:20:58] History is empty, nothing left to delete.
[2024-09-24 16:20:58] Deleted 0 history items.
State changed: Not running
Process finished.

**Comment by apastel** [comment]
That is pretty perplexing. Unfortunately since the [ytmusicapi](https://ytmusicapi.readthedocs.io/en/stable/reference.html#ytmusicapi.YTMusic.get_history) is returning `None`, there's nothing that this app can do to fix that. The only obvious thing I can suggest is to make sure you are logged into YTMusic Deleter with the same account that you're using in YT Music. I've made that mistake since I have several test accounts, but it's probably not what you're experiencing. Unless it is.

Even though it may not be the fault of my app that it isn't working, it still bugs me that users of my app aren't able to use all the features. I want to open this as an issue in [ytmusicapi](https://github.com/sigma67/ytmusicapi) but since I can't replicate it on my own, there's not much info I can give them except "hey, a user says that `get_history()` is returning empty when they say they have history". They would probably want more info like what the browser response object is when you visit the history page. And to open an issue on their project, you would really have to test the ytmusicapi standalone instead of bundled with my app. So you'd have to run a Python script that looks like this:

```py
from ytmusicapi import YTMusic

yt = YTMusic('oauth.json')  # use the oauth.json file that's in %APPDATA&/YTMusic_Deleter
history_items = yt.get_history()
print(history_items)
```
That would work as an isolated example to test the `get_history()` function of ytmusicapi.

I would understand if you didn't want to do all that, or if it would take longer than deleting them manually one-by-one. Of course, if you sent me your "oauth.json" file I could do all this for you, but that's like handing me the keys to your YTMusic account. Not that I would do anything nefarious with it, but I certainly wouldn't send mine to somebody else.
