### ISSUE TITLE
Permission denied on Mac

### ISSUE THREAD

**Issue by essentialols** [apastel/ytmusic-deleter#8]
After installing and adding the install location to my path, I receive 

zsh: permission denied: ytmusic_deleter

I ran chmod 777 on the directory where the file is located but to no avail.

**Comment by apastel** [comment]
Please forgive me as I'm not a Mac developer, but my guess is that this is most likely related to the way in which you are installing and running the program. Without details on that, I can't offer too much help. Since your error mentions `ytmusic_deleter` with an underscore, which is not the name of the binary but the name of the source code directory, it seems like maybe you downloaded the source code and are attempting to run it from the source, or maybe you used pip to install it but are still attempting to run it directly out of the lib folder instead of running the `ytmusic-deleter` command.

If you install the program using pip in a Python virtual environment, you shouldn't have to add anything to your path, and it *should* work the same on Windows/Mac/Linux.

For example, running a series of commands like this:
```
python3 -m venv test-venv           # Creates a virtual env in the current working directory called "test-venv"
source test-venv/bin/active         # Activates that virtual env
pip install ytmusic-deleter         # Install ytmusic-deleter
ytmusic-deleter                     # Run ytmusic-deleter
```
That should work on any operating system, and I would recommend running any & all Python modules in this same fashion as it guarantees a clean environment untainted by any other modules, and eliminates the need for any other configuration, such as adding things to your path or having to change permissions on a directory.
